# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/python:3.0-python3.8-appservice
FROM mcr.microsoft.com/azure-functions/python:3.0-python3.8

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

ENV DEBIAN_FRONTEND=noninteractive

COPY requirements.txt /
RUN pip install -r $(System.DefaultWorkingDirectory)/_ajaygit158_testansible/requirements.txt

RUN apt-get update && \
  apt-get install -y gcc python-dev libkrb5-dev && \
  apt-get install curl && \
  curl -sL https://aka.ms/InstallAzureCLIDeb | bash && \
  pip install pywinrm[kerberos] && \
  apt install krb5-user -y && \ 
  pip install pywinrm && \
  pip install ansible && \
  ansible-galaxy collection install azure.azcollection && \
  pip install -r /home/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

 COPY . /home/site/wwwroot
